// Code generated by ogen, DO NOT EDIT.

package ogent

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateJudgeOperation            OperationName = "CreateJudge"
	CreateProblemOperation          OperationName = "CreateProblem"
	CreateSubmissionOperation       OperationName = "CreateSubmission"
	DeleteJudgeOperation            OperationName = "DeleteJudge"
	DeleteProblemOperation          OperationName = "DeleteProblem"
	DeleteSubmissionOperation       OperationName = "DeleteSubmission"
	HealthCheckOperation            OperationName = "HealthCheck"
	ListJudgeOperation              OperationName = "ListJudge"
	ListJudgeProblemsOperation      OperationName = "ListJudgeProblems"
	ListProblemOperation            OperationName = "ListProblem"
	ListProblemSubmissionsOperation OperationName = "ListProblemSubmissions"
	ListSubmissionOperation         OperationName = "ListSubmission"
	ReadJudgeOperation              OperationName = "ReadJudge"
	ReadProblemOperation            OperationName = "ReadProblem"
	ReadProblemJudgeOperation       OperationName = "ReadProblemJudge"
	ReadSubmissionOperation         OperationName = "ReadSubmission"
	ReadSubmissionProblemOperation  OperationName = "ReadSubmissionProblem"
	UpdateJudgeOperation            OperationName = "UpdateJudge"
	UpdateProblemOperation          OperationName = "UpdateProblem"
	UpdateSubmissionOperation       OperationName = "UpdateSubmission"
)
